ALTER TABLE USERS DROP COLUMN ISQ;
ALTER TABLE USERS DROP COLUMN U_LOGIN;
ALTER TABLE USERS DROP COLUMN PATRONYMIC;

ALTER TABLE TEST_CONFIG DROP COLUMN TC_DUE_DATE;
ALTER TABLE TEST_CONFIG DROP COLUMN TC_TIME_TO_TEST;
ALTER TABLE TEST_CONFIG ADD COLUMN TC_TIME_TO_TEST TINYINT;
ALTER TABLE TEST_CONFIG ADD COLUMN TC_DATE_START DATE;
ALTER TABLE TEST_CONFIG ADD COLUMN TC_DATE_FINISH DATE;
ALTER TABLE TEST_CONFIG ADD COLUMN TC_TITLE VARCHAR(100);

ALTER TABLE TEST_ASSIGNMENT ADD COLUMN TA_COUNT_RIGHT_ANSWERS TINYINT;
ALTER TABLE TEST_ASSIGNMENT CHANGE DATE_REGISTRATION TA_DATE_PASSED DATE;

ALTER TABLE QUESTIONS ADD COLUMN MY_ANSWER BOOLEAN;
ALTER TABLE QUESTIONS ADD COLUMN MANY_ANSWERS BOOLEAN;