ALTER TABLE TEST_ASSIGNMENT DROP COLUMN TA_TEST_START;
ALTER TABLE TEST_ASSIGNMENT DROP COLUMN TA_TEST_FINISH;
ALTER TABLE TEST_ASSIGNMENT ADD COLUMN TA_DATE_START DATE;
ALTER TABLE TEST_ASSIGNMENT ADD COLUMN TA_DATE_FINISH DATE;