CREATE DATABASE IF NOT EXISTS `geekhub` CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE USERS(
  USER_ID INT NOT NULL AUTO_INCREMENT,
  U_LOGIN VARCHAR(25) NOT NULL,
  U_PASSWORD VARCHAR(100) NOT NULL,
  U_REG_DATE DATE NOT NULL,
  FIRST_NAME VARCHAR(25) NOT NULL,
  LAST_NAME VARCHAR(25) NOT NULL,
  PATRONYMIC VARCHAR(25) NOT NULL,
  E_MAIL VARCHAR(40) NOT NULL,
  SKYPE VARCHAR(40),
  ISQ VARCHAR(40),
  PHONE_NUMBER VARCHAR(30) NOT NULL,
  B_DAY DATE NOT NULL,
  ENABLED TINYINT(2) NOT NULL,
  PRIMARY KEY (USER_ID)
) ;

CREATE TABLE ROLES(
  ROLE_ID TINYINT NOT NULL AUTO_INCREMENT,
  ROLE_NAME VARCHAR(10) NOT NULL,
  PRIMARY KEY (ROLE_ID)
) ;
ALTER TABLE ROLES ADD CONSTRAINT ROLES_NAME_UNIQUE UNIQUE (ROLE_NAME);

CREATE TABLE  USER_ROLES(
  UR_USER_ID INT NOT NULL,
  UR_ROLE_ID TINYINT NOT NULL,
  CONSTRAINT FK_USER_ROLES_UID FOREIGN KEY (UR_USER_ID) REFERENCES USERS(USER_ID),
  CONSTRAINT FK_USER_ROLES_ROLE_ID FOREIGN KEY (UR_ROLE_ID) REFERENCES ROLES(ROLE_ID)
);
ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ROLES_Unique UNIQUE (UR_USER_ID,UR_ROLE_ID);

CREATE TABLE COURSES (
	COURSE_ID TINYINT NOT NULL AUTO_INCREMENT,
	COURSE_NAME VARCHAR(30),
	PRIMARY KEY (COURSE_ID)
);
ALTER TABLE COURSES ADD CONSTRAINT COURSES_NAME_UNIQUE UNIQUE (COURSE_NAME);

CREATE TABLE  USER_COURSES(
  UC_USER_ID INT NOT NULL,
  UC_COURSE_ID TINYINT NOT NULL,
  CONSTRAINT FK_USER_COURSES_UID FOREIGN KEY (UC_USER_ID) REFERENCES USERS(USER_ID),
  CONSTRAINT FK_USER_COURSES_COURSE_ID FOREIGN KEY (UC_COURSE_ID) REFERENCES COURSES(COURSE_ID)
);
ALTER TABLE USER_COURSES ADD CONSTRAINT USER_COURSES_Unique UNIQUE (UC_USER_ID,UC_COURSE_ID);