CREATE TABLE IF NOT EXISTS NOTES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	FROM_USER_ID INT UNSIGNED NOT NULL,
	TO_USER_ID INT UNSIGNED NOT NULL,
	TEXT TEXT NOT NULL,
	DATE DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE USERS DROP COLUMN FEEDBACK;
