DROP TABLE IF EXISTS USER_COURSES;
CREATE TABLE USERS_COURSES(
  USERS_COURSES_ID INT NOT NULL AUTO_INCREMENT,
  UC_USER_ID INT NOT NULL,
  UC_COURSE_ID TINYINT NOT NULL,
  PRIMARY KEY (USERS_COURSES_ID)
) ;
