
CREATE TABLE IF NOT EXISTS QUESTIONS(
  QUESTION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  QUESTION_TEXT TEXT NOT NULL,
  QUESTION_WEIGTH TINYINT NOT NULL,

  PRIMARY KEY (QUESTION_ID)
) ;

CREATE TABLE IF NOT EXISTS ANSWERS(
  ANSWER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ANSWER_TEXT TEXT NOT NULL,
  ANSWER_RIGHT BOOLEAN NOT NULL,

  PRIMARY KEY (ANSWER_ID)

) ;