CREATE TABLE TEST_CONFIG(
  TEST_CONFIG_ID INT NOT NULL AUTO_INCREMENT,
  TC_QUESTION_COUNT INT NOT NULL,
  TC_DUE_DATE DATE NOT NULL,
  TC_STATUS VARCHAR(15) NOT  NULL,
  TC_COURSE_ID INT NOT NULL,
  PRIMARY KEY (TEST_CONFIG_ID)
);
CREATE TABLE TEST_ASSIGNMENT (
  TEST_ASSIGNMENT_ID int NOT NULL  AUTO_INCREMENT,
  TA_USER_ID INT NOT NULL,
  TA_TEST_CONFIG_ID INT NOT NULL ,
  DATE_REGISTRATION DATE NOT NULL,
  PRIMARY KEY (TEST_ASSIGNMENT_ID)
);
