CREATE TABLE IF NOT EXISTS USER_RESULTS(
  USER_RESULTS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (USER_RESULTS_ID)
) ;

CREATE TABLE IF NOT EXISTS USER_ANSWERS(
  USER_ANSWERS_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CUSTOM_ANSWERS TEXT,
  PRIMARY KEY (USER_ANSWERS_ID)
) ;