ALTER TABLE TEST_ASSIGNMENT DROP COLUMN DATE_REGISTRATION;
ALTER TABLE TEST_ASSIGNMENT add COLUMN  DATE_REGISTRATION DATE NOT NULL;
ALTER TABLE TEST_ASSIGNMENT add COLUMN  TA_TEST_START DATE NOT NULL;
ALTER TABLE TEST_ASSIGNMENT add COLUMN  TA_TEST_FINISH DATE NOT NULL;
ALTER TABLE TEST_ASSIGNMENT ADD  COLUMN TA_PASSED BOOLEAN NOT NULL;
ALTER TABLE TEST_ASSIGNMENT ADD  COLUMN TA_TEST_STATUS_ASSIGNMENT VARCHAR(15) NOT NULL;
ALTER TABLE COURSES DROP COLUMN COURSE_DESCRIPTION;
ALTER TABLE COURSES ADD  COLUMN COURSE_DESCRIPTION VARCHAR(200);

