ALTER TABLE test_assignment DROP COLUMN DATE_REGISTRATION;
ALTER TABLE test_assignment add COLUMN  DATE_REGISTRATION DATE NOT NULL;
ALTER TABLE test_assignment add COLUMN  TA_TEST_START DATE NOT NULL;
ALTER TABLE test_assignment add COLUMN  TA_TEST_FINISH DATE NOT NULL;
ALTER TABLE test_assignment ADD  COLUMN TA_PASSED BOOLEAN NOT NULL;
ALTER TABLE test_assignment ADD  COLUMN TA_TEST_STATUS_ASSIGNMENT VARCHAR(15) NOT NULL;
ALTER TABLE courses DROP COLUMN COURSE_DESCRIPTION;
ALTER TABLE courses ADD  COLUMN COURSE_DESCRIPTION VARCHAR(200);

