
CREATE TABLE IF NOT EXISTS QUESTIONS(
  QUESTION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  QUESTION_TEXT TEXT NOT NULL,
  QUESTION_WEIGTH TINYINT NOT NULL,
  COURSE_ID TINYINT NOT NULL,
  CONSTRAINT FK_QUESTIONS_COURSES_COURSE_ID FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID),

  PRIMARY KEY (QUESTION_ID)
) ;

CREATE TABLE IF NOT EXISTS ANSWERS(
  ANSWER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ANSWER_TEXT TEXT NOT NULL,
  ANSWER_RIGHT BOOLEAN NOT NULL,
  QUESTION_ID INT UNSIGNED NOT NULL,
  CONSTRAINT FK_ANSWERS_QUESTIONS_QUESTION_ID FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID),
  PRIMARY KEY (ANSWER_ID)

) ;