CREATE DATABASE `geekhub` CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE USERS(
  USER_ID INT NOT NULL AUTO_INCREMENT,
  U_LOGIN VARCHAR(25) NOT NULL,
  U_PASSWORD VARCHAR(100) NOT NULL,
  U_REG_DATE DATE NOT NULL, 
  FIRST_NAME VARCHAR(25) NOT NULL,
  LAST_NAME VARCHAR(25) NOT NULL,
  PATRONYMIC VARCHAR(25) NOT NULL, 
  E_MAIL VARCHAR(40) NOT NULL,
  SKYPE VARCHAR(40),
  ICQ VARCHAR(40), 
  PHONE_NUMBER VARCHAR(30) NOT NULL,
  B_DAY DATE NOT NULL,
  ENABLED TINYINT(2) NOT NULL, 
  PRIMARY KEY (USER_ID)
) ;
ALTER TABLE USERS ADD CONSTRAINT USERS_DATA_UNIQUE UNIQUE(U_LOGIN,E_MAIL,SKYPE);
ALTER TABLE USERS ADD CONSTRAINT USERS_LOGIN_UNIQUE UNIQUE(U_LOGIN);
ALTER TABLE USERS ADD CONSTRAINT USERS_EMAIL_UNIQUE UNIQUE(E_MAIL);
ALTER TABLE USERS ADD CONSTRAINT USERS_SKYPE_UNIQUE UNIQUE(SKYPE);

INSERT INTO USERS (U_LOGIN,U_PASSWORD,U_REG_DATE,FIRST_NAME,LAST_NAME,PATRONYMIC,E_MAIL,SKYPE,ICQ,PHONE_NUMBER,B_DAY,ENABLED) VALUES ('Odahovskiy','e10adc3949ba59abbe56e057f20f883e','2015-05-13','Володимир','Одаховський','Юрійович','odahovskiy@gmail.com','babygluk','411837166','+380(93)145-15-14','1994-03-04','1');
INSERT INTO USERS (U_LOGIN,U_PASSWORD,U_REG_DATE,FIRST_NAME,LAST_NAME,PATRONYMIC,E_MAIL,SKYPE,ICQ,PHONE_NUMBER,B_DAY,ENABLED) VALUES ('Petrovich','e10adc3949ba59abbe56e057f20f883e','2015-05-12','Владислав','Олексійченко','Олегович','oleksiuk91@gmail.com',NULL,NULL,'+380(93)145-15-14','1996-01-09','1');
INSERT INTO USERS (U_LOGIN,U_PASSWORD,U_REG_DATE,FIRST_NAME,LAST_NAME,PATRONYMIC,E_MAIL,SKYPE,ICQ,PHONE_NUMBER,B_DAY,ENABLED) VALUES ('PZahar','e10adc3949ba59abbe56e057f20f883e','2015-05-13','Петро','Захарченко','Юрійович','p.zahar@gmail.com','zahar081',NULL,'+380(93)455-25-99','1984-03-12','1');
INSERT INTO USERS (U_LOGIN,U_PASSWORD,U_REG_DATE,FIRST_NAME,LAST_NAME,PATRONYMIC,E_MAIL,SKYPE,ICQ,PHONE_NUMBER,B_DAY,ENABLED) VALUES ('kuzia','e10adc3949ba59abbe56e057f20f883e','2015-05-11','Євгеній','Кузевич','Андрійович','e.kuzia@gmail.com','kuzia94','344122456','+380(97)561-45-19','1993-12-04','1');
INSERT INTO USERS (U_LOGIN,U_PASSWORD,U_REG_DATE,FIRST_NAME,LAST_NAME,PATRONYMIC,E_MAIL,SKYPE,ICQ,PHONE_NUMBER,B_DAY,ENABLED) VALUES ('mihailyk','e10adc3949ba59abbe56e057f20f883e','2015-05-10','Олексій','Михайлюк','Михайлович','olex.myh@gmail.com','myhailuk','874123493','+380(67)355-19-44','1964-05-12','1');

CREATE TABLE ROLES(
  ROLE_ID TINYINT NOT NULL AUTO_INCREMENT,
  ROLE_NAME VARCHAR(25) NOT NULL,
  PRIMARY KEY (ROLE_ID)
) ;
ALTER TABLE ROLES ADD CONSTRAINT ROLES_NAME_UNIQUE UNIQUE (ROLE_NAME);
INSERT INTO ROLES (ROLE_NAME) VALUES('ADMIN');
INSERT INTO ROLES (ROLE_NAME) VALUES('TEACHER');
INSERT INTO ROLES (ROLE_NAME) VALUES('STUDENT');
INSERT INTO ROLES (ROLE_NAME) VALUES('ABITURIENT');
INSERT INTO ROLES (ROLE_NAME) VALUES('FREE_LISTENER');
INSERT INTO ROLES (ROLE_NAME) VALUES('PRE_STUDENT');

CREATE TABLE  USER_ROLES(
  UR_USER_ID INT NOT NULL,
  UR_ROLE_ID TINYINT NOT NULL,
  CONSTRAINT FK_USER_ROLES_UID FOREIGN KEY (UR_USER_ID) REFERENCES USERS(USER_ID),
  CONSTRAINT FK_USER_ROLES_ROLE_ID FOREIGN KEY (UR_ROLE_ID) REFERENCES ROLES(ROLE_ID)
);
ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ROLES_Unique UNIQUE (UR_USER_ID,UR_ROLE_ID);
INSERT INTO USER_ROLES (UR_USER_ID,UR_ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLES (UR_USER_ID,UR_ROLE_ID) VALUES (2,3);
INSERT INTO USER_ROLES (UR_USER_ID,UR_ROLE_ID) VALUES (3,3);
INSERT INTO USER_ROLES (UR_USER_ID,UR_ROLE_ID) VALUES (4,3);
INSERT INTO USER_ROLES (UR_USER_ID,UR_ROLE_ID) VALUES (5,3);

CREATE TABLE COURSES (
	COURSE_ID TINYINT NOT NULL AUTO_INCREMENT,
	COURSE_NAME VARCHAR(30) NOT NULL,
	DESCRIPTION VARCHAR(3000) NOT NULL,
	THEMES_ON_EXAMS VARCHAR(1000) NOT NULL,
	WORD_FROM_TEACHERS(3000),
	PRIMARY KEY (COURSE_ID)
);
ALTER TABLE COURSES ADD CONSTRAINT COURSES_NAME_UNIQUE UNIQUE (COURSE_NAME);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Frontend+CMS','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Advanced CMS','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Advanced PHP','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Java Script','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('IOS','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Android','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Runy on Rails','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Groovy & Grails','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Java for Web','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Project Managment','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Quality Assurance','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Business English','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Web & mobile design','Description...','.....',NULL);
INSERT INTO COURSES (COURSE_NAME,DESCRIPTION,THEMES_ON_EXAMS,WORD_FROM_TEACHERS) VALUES ('Game Production','Description...','.....',NULL);

CREATE TABLE  USER_COURSES(
  UC_USER_ID INT NOT NULL,
  UC_COURSE_ID TINYINT NOT NULL,
  CONSTRAINT FK_USER_COURSES_UID FOREIGN KEY (UC_USER_ID) REFERENCES USERS(USER_ID),
  CONSTRAINT FK_USER_COURSES_COURSE_ID FOREIGN KEY (UC_COURSE_ID) REFERENCES COURSES(COURSE_ID)
);
ALTER TABLE USER_COURSES ADD CONSTRAINT USER_COURSES_Unique UNIQUE (UC_USER_ID,UC_COURSE_ID);
INSERT INTO USER_COURSES (UC_USER_ID,UC_COURSE_ID) VALUES (1,1);
INSERT INTO USER_COURSES (UC_USER_ID,UC_COURSE_ID) VALUES (2,3);
INSERT INTO USER_COURSES (UC_USER_ID,UC_COURSE_ID) VALUES (3,5);
INSERT INTO USER_COURSES (UC_USER_ID,UC_COURSE_ID) VALUES (4,5);
INSERT INTO USER_COURSES (UC_USER_ID,UC_COURSE_ID) VALUES (5,9);
